apiVersion: v2
name: sqlite-litestream
description: Helm chart for sqlite-litestream
type: application
version: 0.1.0
appVersion: "0.1.0"

# License of the packaged application. ArtifactHub reads this annotation.
annotations:
  artifacthub.io/license: Apache-2.0
sources:
  - https://github.com/fabiocicerchia/sqlite-litestream
